# Generated by Django 4.0.3 on 2023-04-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('score', models.FloatField(default=0)),
                ('latitude', models.DecimalField(decimal_places=14, max_digits=16)),
                ('longitude', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
    ]
